from enum import Enum


class MarketRegime(str, Enum):
    LOW_VOL_RANGE = "LOW_VOL_RANGE"
    NORMAL_RANGE = "NORMAL_RANGE"
    TREND_UP = "TREND_UP"
    TREND_DOWN = "TREND_DOWN"
    HIGH_VOL = "HIGH_VOL"
    VOLATILITY_EXPANSION = "VOLATILITY_EXPANSION"
    EXTREME_FUNDING = "EXTREME_FUNDING"
    LIQUIDATION_STYLE_MOVE = "LIQUIDATION_STYLE_MOVE"
    UNKNOWN = "UNKNOWN"

